SIM           = icarus
TOPLEVEL_LANG = verilog
SIM_BUILD     = sim_build_q15_tanh

VERILOG_SOURCES = $(PWD)/../rtl/q15_tanh.sv
TOPLEVEL        = q15_tanh
MODULE          = test_q15_tanh

COMPILE_ARGS    = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
