SIM           = icarus
TOPLEVEL_LANG = verilog
SIM_BUILD     = sim_build_q15_blend

VERILOG_SOURCES = $(PWD)/../rtl/q15_blend.sv
TOPLEVEL        = q15_blend
MODULE          = test_q15_blend

COMPILE_ARGS    = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
