SIM           = icarus
TOPLEVEL_LANG = verilog
SIM_BUILD     = sim_build_compute_core

VERILOG_SOURCES = \
    $(PWD)/../rtl/q15_mac.sv \
    $(PWD)/../rtl/q15_tanh.sv \
    $(PWD)/../rtl/q15_blend.sv \
    $(PWD)/../rtl/compute_core.sv \
    $(PWD)/dump_waves.sv

TOPLEVEL        = compute_core
MODULE          = test_compute_core

COMPILE_ARGS    = -g2012 -s dump_waves

include $(shell cocotb-config --makefiles)/Makefile.sim
