SIM           = icarus
TOPLEVEL_LANG = verilog
SIM_BUILD     = sim_build_interface

VERILOG_SOURCES = \
    $(PWD)/../rtl/q15_mac.sv \
    $(PWD)/../rtl/q15_tanh.sv \
    $(PWD)/../rtl/q15_blend.sv \
    $(PWD)/../rtl/compute_core.sv \
    $(PWD)/../rtl/interface.sv

TOPLEVEL        = interface_axi
MODULE          = test_interface

COMPILE_ARGS    = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
