SIM             = icarus
TOPLEVEL_LANG   = verilog
VERILOG_SOURCES = $(PWD)/esn_core.sv
TOPLEVEL        = esn_core
MODULE          = test_esn_core

include $(shell cocotb-config --makefiles)/Makefile.sim
