SIM          = icarus
TOPLEVEL_LANG = verilog

VERILOG_SOURCES = $(PWD)/mac_correct.sv
TOPLEVEL        = mac_correct
MODULE          = test_mac

COMPILE_ARGS    = -g2012

include $(shell cocotb-config --makefiles)/Makefile.sim
